Document: dircnt
Title: Debian dircnt Manual
Author: <insert document author here>
Abstract: This manual describes what dircnt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dircnt/dircnt.sgml.gz

Format: postscript
Files: /usr/share/doc/dircnt/dircnt.ps.gz

Format: text
Files: /usr/share/doc/dircnt/dircnt.text.gz

Format: HTML
Index: /usr/share/doc/dircnt/html/index.html
Files: /usr/share/doc/dircnt/html/*.html
